---
title: "Intro"
output: blogdown::html_page
menu:
  docs:
    parent: "syllabus"
weight: 100
toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Course description

**Data science** is the practice of extracting insights from large amounts of quantitative data. Rigorous data science requires two things:

- the _technical skill_ to make sense of patterns in data
- the _logical skill_ to understand those patterns in the context of the world that generated those data

This course aims to introduce students to _**scientific** computing,_ which encompasses both of those technical and logical skills. In general, this aims to _inspire excitement and curiosity about the uses, pitfalls, and joys of programming for scientists._

## Learning objectives

By the end of this project course, students will be able to…

- Design a research question of personal interest that can be answered with publicly available data
- Source a dataset that can answer said research question
- Explain the contents of the dataset and evaluate potential error and bias in the data
- Inspect the data, clean the data, and prepare it for analysis
- Visually analyze the data by generating exploratory graphs
- Generate presentation graphs to communicate meaningful patterns in the data
- Identify and debug commonplace R errors
- Design clear, engaging, and informative presentations of results

## Course format

This course will consist mainly of interactive code-along lectures, interspersed with solo and group work time on in-class activities and exercises.
